### ISSUE TITLE
shulker boxes dont save item changes

### ISSUE THREAD

**Issue by TorbenB03** [atombuilt/atom-shulkers#1]
Opening a shulker in your hand and putting items in it deletes the items from the game, the shulker remains empty.
Taking items out of a shulker dupes them as they remain in the shulker and are also added to the players inventory.

Tested on paper 1.20.2 build #318

**Comment by shorinami** [comment]
Hello, looking into the issue!
I have tested the plugin on an empty server, Paper 1.20.2 build #318, and it works as expected.
So I expect it should be related to the other plugins you have on your server.
In case there are any errors in the console log, would be great if you could provide those.
As of now I fixed the isolation issue in the respective branch.
Try this version, and let me know if it 

[atom-shulkers-1.0.1.jar.zip](https://github.com/atombuilt/atom-shulkers/files/13758240/atom-shulkers-1.0.1.jar.zip)
